# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepost',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
