# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0003_friends_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepost',
            name='send_to',
            field=models.ManyToManyField(related_name='received_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
