# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_friendshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviepost',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
