# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_auto_20170209_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepost',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
