# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
