# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_auto_20170301_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
